### ISSUE TITLE
Error in ustvnow plugin on linux

### ISSUE THREAD

**Issue by dmdeklerk** [t0mm0/t0mm0-xbmc-plugins#16]
Running the latest Eden on xbmcbuntu I get the following error after installing and running the ustvnow version 0.3.0.

11:30:44 T:2910845760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'output'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.xbmc/addons/plugin.video.ustvnow/default.py", line 32, in <module>
                                                Addon.log('plugin url: ' + Addon.plugin_url)
                                              File "/home/xbmc/.xbmc/addons/plugin.video.ustvnow/resources/lib/Addon.py", line 39, in log
                                                xbmc.output(addon.getAddonInfo('name') + ': ' + msg.encode('utf-8'),
                                            AttributeError: 'module' object has no attribute 'output'
                                            -->End of Python script error report<--

**Comment by itjstagame** [comment]
I ran in to the same issue on Raspbmc linux.  I am not sure what is different about Frodo or the release that 0.3.0 ustvnow was built for, but xbmc does not have an 'output' option.

I simply opened up "/home/xbmc/.xbmc/addons/plugin.video.ustvnow/resources/lib/Addon.py" and changed .output to .log .  Then recompile (pycompile).

This is working great for me now on Raspbmc.

**Comment by RBS-Julian** [comment]
Great solution "itjstagame"

I tried this on windows 7 by going into the Appdata folder for XBMC and it work like a charm.

Thanks or the advice!

**Comment by gilgamezh** [comment]
Some fix here on xbian.  
I edit the line 38 of /home/xbian/.xbmc/addons/plugin.video.crackle/resources/lib/Addon.py changing output for log.
Then i ran pycompile /home/xbian/.xbmc/addons/plugin.video.crackle/resources/lib/Addon.py
the plugins wors after this change :)
